// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FlowTree: typeof import('./src/components/FlowTree.vue')['default']
    FlowView: typeof import('./src/components/FlowView.vue')['default']
    MaterialTable: typeof import('./src/components/MaterialTable.vue')['default']
  }
}
