// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategorySelect: typeof import('./src/components/config_editor/CategorySelect.vue')['default']
    ConfigEditor: typeof import('./src/components/config_editor/ConfigEditor.vue')['default']
    ConfigEditorSection: typeof import('./src/components/config_editor/ConfigEditorSection.vue')['default']
    ConfigMachineSection: typeof import('./src/components/config_editor/ConfigMachineSection.vue')['default']
    ConfigMachineView: typeof import('./src/components/config_editor/ConfigMachineView.vue')['default']
    ConfigRecipeSearch: typeof import('./src/components/config_editor/ConfigRecipeSearch.vue')['default']
    ConfigRecipeSection: typeof import('./src/components/config_editor/ConfigRecipeSection.vue')['default']
    ConfigRecipeView: typeof import('./src/components/config_editor/ConfigRecipeView.vue')['default']
    FlowTree: typeof import('./src/components/FlowTree.vue')['default']
    FlowView: typeof import('./src/components/FlowView.vue')['default']
    ImageSection: typeof import('./src/components/config_editor/ImageSection.vue')['default']
    MachineCategorySection: typeof import('./src/components/config_editor/MachineCategorySection.vue')['default']
    MachineSelect: typeof import('./src/components/config_editor/MachineSelect.vue')['default']
    MaterialCategorySection: typeof import('./src/components/config_editor/MaterialCategorySection.vue')['default']
    MaterialSection: typeof import('./src/components/config_editor/MaterialSection.vue')['default']
    MaterialSelect: typeof import('./src/components/config_editor/MaterialSelect.vue')['default']
    MaterialStateSelect: typeof import('./src/components/config_editor/MaterialStateSelect.vue')['default']
    MaterialTable: typeof import('./src/components/MaterialTable.vue')['default']
    Sample: typeof import('./src/components/config_editor/sample.vue')['default']
  }
}
